### ISSUE TITLE
Удалить таб статистики — 00:30

### ISSUE THREAD

**Issue by AndreiChenchik** [BlackBullSquad/iOS-FakeNFT-StarterProject-Public#21]

**Comment by maxim-papier** [comment]
- [ ] Вычистил storyboards
- [ ] Добавил пустые VC для основных разделов (профиль, каталог, корзина)
- [ ] Настроил navbar и tabbar контроллеры в sceneDelegate
- [ ] Добавил assets цветов из Figma
- [ ] Убрал ненужный код из расширения UIColor
- [ ] Сгруппировал, используя enum, цвета для удобства использования. Пример получения цвета:

```swift
let color: UIColor = .appColor(.primary)
```

**Comment by maxim-papier** [comment]
PR: https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/pull/54 (ссылка на него есть и в правой колонке, в Linked pull requests
