### ISSUE TITLE
Иконка (аватарка) NFT eta 1:00, spent 4:00

### ISSUE THREAD

**Issue by AndreiChenchik** [BlackBullSquad/iOS-FakeNFT-StarterProject-Public#37]
### Где будет использована
- Коллекции со списком NFT
- Экраны NFT

### Требования
Т.к. будет использована в коллекциях вьюха будет переиспользоваться в ячейках, соотв она должна удобно обновляться.

- должна быть структура ViewModel
- при обновлении VM вьюха должна сама себя перерисовывать
- лайк тапабельный

### Данные (VM)
- Размер
- Статус Лайка
- Изображение (URL)
- Кложура на лайк

### Размеры
- 108х108
- 80х80

```
// Пример интерфейса (НЕ ОБЯЗАТЕЛЬНО ДЕЛАТЬ ТАК ЖЕ)

let vm = NFTPicViewModel(
	size: .108,
	isLiked: true,
	imageURL: "http://ya.ru"
) { isLiked in
	print("update to \(isLiked)")
} 
let view = NFTPicView(model: vm)
// 3 hours later
let newVM = NFTPicViewModel(
	size: .108,
	isLiked: false,
	imageURL: "http://google.com"
) { isLiked in
	print("update to \(isLiked)")
} 
view.model = newVM // <-- view will update itself
```

**Comment by maxim-papier** [comment]
Обновил согласно переработанному ТЗ. Теперь имени на аватарке нет и фона под ним тоже. Таким образом разница теперь только в размерах.


Теперь так
![Image](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/b11b38b7-d5ba-4493-8434-b0903e0eacfb)

А не так
~~<img width="265" alt="image" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/217896/9f2c6385-f24a-4357-a33c-f43dc63e4c9e">~~

**Comment by maxim-papier** [comment]
Сделано. Инстанс создаётся так:

``` swift
let imageURL = URL(string: "https://podarki.ru/gate/8d850520-0bde-4922-a1f1-b203cf177234/links-set/3af29402-0255-4f56-83fc-6d32cadf7b48/picture/96de30c0-da5a-4caf-8a25-3fed979df1ed.jpg")
        let viewModel = NFTAvatarViewModel(
            imageSize: .large,
            imageURL: imageURL,
            isLiked: false,
            likeButtonAction: {
                print("Like button was tapped!")
            }
        )
```

Аватар-иконка NFT существует в двух размерах 108x108 и 80x80. В модели я назвал их .large и .small, но в фигме таких названий нет. Как считаете, может лучше назвать .108 и .80?

Пытался использовать KingFisher для скругления, но что-то упёрся в проблему с проступающим из-под imageView плейсхолдером. 

Placeholder сейчас в формате png, пытался использовать .svg, но он никак не подцелплялся. Могу разобраться, но если не критично, но оставим png.

Таким образом, парни, жду от вас:
- Всё ли ок в общем
- Не надо ли поменять нейминг размеров c .small и .large на .80 и .108 соответственно 
- Оставляем ли плейсхолдер в формате png или всё же нужен svg.

**Comment by maxim-papier** [comment]
Сделал такой метод в аватаре:

```swift
private func reset() {
	imageView.image = nil
	likeButton.tintColor = .asset(.main(.primary))
	likeButton.setImage(UIImage(systemName: "hear.fill"), for: .normal)
}
```

Его можно будет вызывать в ваших ячейках, чтобы при переиспользовании всё очищалось следующим образом:

```swift
override func prepareForReuse() {
    super.prepareForReuse()
    avatarView.configure(with: nil)
}
```

**Comment by maxim-papier** [comment]
готово

**Comment by maxim-papier** [comment]
готово
